version = 1


[merge]
method = "squash" 
automerge_label = "automerge 🚀"
prioritize_ready_to_merge = true 

[merge.message]
title = "pull_request_title"

[approve]
auto_approve_usernames = ["dependabot"]
